### GET ALL
GET http://localhost:8889/api/v1/addresses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0YzVmMDI1MTYwYjIyNGY0MTFlNjEiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0QGdtYWlsLmNvbSIsImlhdCI6MTc0NDE3MDc4OCwiZXhwIjoxNzQ0MjU3MTg4fQ.t0z_EeHQTDuyvX1GJEEr-YY4LfC17rgq1Hg4GYxw5g8

### get by id
GET http://localhost:8889/api/v1/addresses/67f5f02a949fae1bc997e44e
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0YzVmMDI1MTYwYjIyNGY0MTFlNjEiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0QGdtYWlsLmNvbSIsImlhdCI6MTc0NDE2ODc2MiwiZXhwIjoxNzQ0MjU1MTYyfQ.am9xaH3J7E36zYHTx0BY-eXlhl1vJs6gbboJQWAo9RM

### create

POST http://localhost:8889/api/v1/addresses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0YzVmMDI1MTYwYjIyNGY0MTFlNjEiLCJlbWFpbCI6Im5ndXllbmhvdGhlZGF0QGdtYWlsLmNvbSIsImlhdCI6MTc0NDE2ODc2MiwiZXhwIjoxNzQ0MjU1MTYyfQ.am9xaH3J7E36zYHTx0BY-eXlhl1vJs6gbboJQWAo9RM

{
    "type": "shipping",
    "fullName": "Nguyễn Hồ Thế Đạt",
    "phoneNumber": "0905273001",
    "street": "20 Bầu Tràm",
    "ward": "Hòa Sơn",
    "district": "Hòa Vang",
    "city": "Da Nang",
    "country": "Việt Nam",
    "isDefault": true,
    "user": "6800a1756acc4bfbf1fc7759"
}

### update by id
PUT http://localhost:8889/api/v1/addresses/67d9452369975e3a9c1c24cc
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2UyNWMzM2EzMTcyMWM3ZGFiOTQyNzciLCJlbWFpbCI6ImRhdG5ndXllbmhvdGhlQGdtYWlsLmNvbSIsImlhdCI6MTc0MzA0MTU3NywiZXhwIjoxNzQzMTI3OTc3fQ.SohKOzQiMD4wgKf1_QPSKwwnbkIlKb7IfYDWuhxWOCQ

{
    "thumbnail": "http://localhost:8889/uploads/addresses/scanner.png"
}

### delete by id
DELETE http://localhost:8889/api/v1/addresses/67d792aba8fc6e96d2595f37